### ISSUE TITLE
reactR example with selectize.js and leaflet

### ISSUE THREAD

**Issue by TrantorM** [timelyportfolio/reactR#1]
Is it possible to use reactR with selectize.js and leaflet?

I try to do [this minimal shiny app](https://geographica.shinyapps.io/Minimalexample/), but without shiny. It's a leaflet choropleth map with a topojson. With the input panel you can select which property of the topojson (integer) should be used for choropleth. Could this be done with reactR?

```
library(shiny)
library(leaflet)
library(leaflet.extras)   # devtools::install_github('bhaskarvk/leaflet.extras')
library(readr)


# Define UI for application that draws a histogram
ui <- fluidPage(
   
   # Application title
   titlePanel("Minimal shiny example for a leaflet choropleth with selectable properties of the underlying topojson"),
   
   # Input panel to select the desired property of the topojson
   inputPanel(
     selectInput("prop", label = "Property:",choices = c('incidents','dist_num'), selected = 'incidents')
   ),
   
   # Map below sidebar layout
   leafletOutput("map")
)

# server logic to draw a leaflet
server <- function(input, output) {
   
topojson <- read_file('https://rawgit.com/TrantorM/leaflet-choropleth/gh-pages/examples/basic_topo/crimes_by_district.topojson')

 output$map <- renderLeaflet({
     property = input$prop
     leaflet() %>% 
       setView(-75.14, 40, zoom = 11) %>%
       addProviderTiles("CartoDB.Positron") %>% 
       addGeoJSONChoropleth(
         topojson,
         valueProperty =property
       )
   })
   
}

# Run the application 
shinyApp(ui = ui, server = server)
```

I also asked in [stackoverflow](http://stackoverflow.com/questions/42013913/reactive-selection-of-json-property-in-r-for-leaflet-without-shiny) regarding this problem.

**Comment by timelyportfolio** [comment]
@TrantorM, sorry I never saw this or the StackOverflow (on there sporadically).  Will discuss on the `vueR` issue for now.

**Comment by timelyportfolio** [comment]
going to close for now... feel free to reopen.  I think there is a good chance that `reactR` will get some more functionality soon.
