### ISSUE TITLE
add core-js

### ISSUE THREAD

**Issue by timelyportfolio** [timelyportfolio/reactR#3]
Add core-js dependency, so will appear in RStudio Viewer.  ref #2

**Comment by saurfang** [comment]
Have you tried RStudio daily builds? I think 1.2 upgraded from QTWebkit to QtWebEngine and supposedly uses a much newer variant of chromium. Your examples render in my viewer pane just fine.

**Comment by timelyportfolio** [comment]
done in https://github.com/timelyportfolio/reactR/releases/tag/v0.2.0
